#!/usr/bin/env node
// build-scripts/generate-install.mjs
//
// Reads PollService/templates/PollService-install-template.sh, substitutes
// the {{NODE_MAJOR}} and {{REPO}} placeholders from PollService/package.json
// and releases.json respectively, and writes the result to
// PollService/scripts/install.sh.
//
// Invoked automatically as Step 1 of build-scripts/build.mjs. Can also be run
// directly during development:
//
//   node build-scripts/generate-install.mjs
import { readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');

// ── Extract NODE_MAJOR from PollService/package.json ──────────────────────────

function extractNodeMajor() {
  const pkgPath = resolve(REPO_ROOT, 'PollService', 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const raw = pkg.devDependencies?.['@types/node'] ?? '';
  if (!raw) {
    throw new Error('PollService/package.json has no devDependencies["@types/node"] entry.');
  }
  // Strip any leading semver range operators (^, ~, >=, >, <=, <, =) and whitespace.
  const stripped = raw.replace(/^[\^~><=\s]+/, '');
  // Take only the integer before the first dot (handles "22.0.0", "22.x", "22" alike).
  const major = stripped.split('.')[0];
  if (!major || !/^\d+$/.test(major)) {
    throw new Error(
      `Could not parse a Node.js major version number from @types/node value: "${raw}"`
    );
  }
  return major;
}

// ── Extract REPO from releases.json ──────────────────────────────────────────

function extractRepo() {
  const releasesPath = resolve(REPO_ROOT, 'releases.json');
  const releases = JSON.parse(readFileSync(releasesPath, 'utf8'));
  if (!releases.repo) {
    throw new Error('releases.json is missing the top-level "repo" field.');
  }
  return releases.repo;
}

// ── Substitute and write ──────────────────────────────────────────────────────

const nodeMajor = extractNodeMajor();
const repo = extractRepo();

const templatePath = resolve(
  REPO_ROOT,
  'PollService',
  'templates',
  'PollService-install-template.sh'
);
const outputPath = resolve(REPO_ROOT, 'PollService', 'scripts', 'install.sh');

let template = readFileSync(templatePath, 'utf8');
template = template.replaceAll('{{NODE_MAJOR}}', nodeMajor);
template = template.replaceAll('{{REPO}}', repo);

// Inject the "generated file" header lines immediately after the shebang.
// These comments are intentionally absent from the template so developers
// editing the template are not confused by them.
const GENERATED_HEADER = [
  '# GENERATED FILE — do not edit this file directly.',
  '# Source: PollService/templates/PollService-install-template.sh'
].join('\n');
template = template.replace('#!/usr/bin/env bash\n', `#!/usr/bin/env bash\n${GENERATED_HEADER}\n`);

// Preserve the executable bit (0o755) expected on a shell script.
writeFileSync(outputPath, template, { mode: 0o755 });

console.log(
  `[generate-install] NODE_MAJOR=${nodeMajor}, REPO=${repo} → PollService/scripts/install.sh`
);
